title: Martin Körner
email: info@mkoerner.de
description: >
  My personal website.
baseurl: "" 
url: https://mkoerner.de
twitter_username: mkrnr
github_username: mkrnr

# Build settings
markdown: kramdown
theme: personal-website-theme

exclude:
  - Gemfile
  - Gemfile.lock
