title: Martin Körner
email: info@mkoerner.de
description: >
  My personal website.
baseurl: ""
url: "https://mkoerner.de"
media_url: "https://media.mkoerner.de"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: mkrnr
    github: mkrnr
    rss: rss

disqus:
  shortname: mkrnr

permalink: /:title/

header_pages:
 - index.md
 - cv/cv.md
 - about.md

# Build settings
markdown: kramdown
theme: personal-website-theme
gems:
  - jekyll-feed
  - jekyll-seo-tag 

