title: Martin Körner
email: info@mkoerner.de
description: >
  My personal website.
baseurl: ""
url: "https://mkoerner.de"
media_url: "https://media.mkoerner.de"
twitter_username: mkrnr
github_username: mkrnr

disqus:
  shortname: mkrnr

permalink: /:title/

header_pages:
 - index.md
 - cv/cv.md
 - about.md

# Build settings
markdown: kramdown
theme: personal-website-theme
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
